import { dataset } from "./dataset";
import { corridorDestsForNat } from "./corridor-dests.mjs";
// Corridors that measurably receive search traffic, from a Search Console
// export. Generated by scripts/build-prerender-list.mjs; see preWarmCorridorPairs().
import PRERENDER from "@/data/prerender-corridors.json";

// Highest-search-volume visa corridors ("<destination> visa for <nationality>").
// Curated subset (top nationalities × top destinations) so the build stays lean
// and Google can crawl/index quickly; expandable later.
export const TOP_NATIONALITIES = [
  "IND", "PAK", "BGD", "NPL", "LKA", "CHN", "PHL", "IDN", "VNM", "MYS",
  "THA", "NGA", "EGY", "KEN", "GHA", "ZAF", "MAR", "DZA", "ETH", "USA",
  "CAN", "MEX", "BRA", "GBR", "DEU", "FRA", "ITA", "ESP", "NLD", "RUS",
  "TUR", "UKR", "POL", "SAU", "ARE", "QAT", "IRN", "JOR", "AUS", "KAZ",
  "BEL",
];
export const TOP_DESTINATIONS = [
  "ARE", "THA", "USA", "GBR", "DEU", "FRA", "ITA", "ESP", "NLD", "GRC",
  "CHE", "PRT", "AUT", "BEL", "SGP", "MYS", "IDN", "VNM", "LKA", "NPL",
  "MDV", "SAU", "QAT", "TUR", "OMN", "BHR", "KWT", "JOR", "CAN", "AUS",
  "NZL", "JPN", "KOR", "CHN", "HKG", "IND", "PHL", "EGY", "KEN", "ZAF",
  "MAR", "TZA", "BRA", "MEX", "ARG", "RUS", "GEO", "AZE", "KAZ", "UZB",
  "IRL",
];

// The high-search-demand FORCE_CORRIDORS list and the shared thin-content
// quality bar now live in ./corridor-dests.mjs, which is also what
// scripts/build-explorer-slices.mjs uses to emit per-passport corridor sets
// for the client explorers - one implementation, no drift.

/** Adjectival demonym, e.g. "Thailand Visa for Indian citizens". Copy that uses
 * this map must fall back to a phrasing that reads correctly with the bare
 * country name (e.g. "Palau passport holders", "citizens of Palau"). */
export const DEMONYM: Record<string, string> = {
  // Top corridor nationalities
  IND: "Indian", PAK: "Pakistani", BGD: "Bangladeshi", NPL: "Nepali", LKA: "Sri Lankan",
  CHN: "Chinese", PHL: "Filipino", IDN: "Indonesian", VNM: "Vietnamese", MYS: "Malaysian",
  THA: "Thai", NGA: "Nigerian", EGY: "Egyptian", KEN: "Kenyan", GHA: "Ghanaian",
  ZAF: "South African", MAR: "Moroccan", DZA: "Algerian", ETH: "Ethiopian", USA: "American",
  CAN: "Canadian", MEX: "Mexican", BRA: "Brazilian", GBR: "British", DEU: "German",
  FRA: "French", ITA: "Italian", ESP: "Spanish", NLD: "Dutch", RUS: "Russian",
  TUR: "Turkish", UKR: "Ukrainian", POL: "Polish", SAU: "Saudi", ARE: "Emirati",
  QAT: "Qatari", IRN: "Iranian", JOR: "Jordanian", AUS: "Australian", KAZ: "Kazakh",
  BEL: "Belgian",
  // Broader coverage for passport-page and guide copy
  JPN: "Japanese", KOR: "South Korean", TWN: "Taiwanese", SGP: "Singaporean",
  CHE: "Swiss", IRL: "Irish", PRT: "Portuguese", GRC: "Greek", AUT: "Austrian",
  NOR: "Norwegian", SWE: "Swedish", DNK: "Danish", FIN: "Finnish", ISL: "Icelandic",
  CZE: "Czech", HUN: "Hungarian", ROU: "Romanian", BGR: "Bulgarian", HRV: "Croatian",
  SVK: "Slovak", SVN: "Slovenian", EST: "Estonian", LVA: "Latvian", LTU: "Lithuanian",
  LUX: "Luxembourgish", MLT: "Maltese", CYP: "Cypriot", ALB: "Albanian", SRB: "Serbian",
  MNE: "Montenegrin", MKD: "Macedonian", BIH: "Bosnian", MDA: "Moldovan", BLR: "Belarusian",
  GEO: "Georgian", ARM: "Armenian", AZE: "Azerbaijani",
  ARG: "Argentine", CHL: "Chilean", COL: "Colombian", PER: "Peruvian", VEN: "Venezuelan",
  ECU: "Ecuadorian", URY: "Uruguayan", PRY: "Paraguayan", BOL: "Bolivian", CRI: "Costa Rican",
  PAN: "Panamanian", GTM: "Guatemalan", HND: "Honduran", SLV: "Salvadoran", NIC: "Nicaraguan",
  CUB: "Cuban", DOM: "Dominican", JAM: "Jamaican", HTI: "Haitian",
  ISR: "Israeli", LBN: "Lebanese", SYR: "Syrian", IRQ: "Iraqi", KWT: "Kuwaiti",
  OMN: "Omani", BHR: "Bahraini", YEM: "Yemeni", LBY: "Libyan", TUN: "Tunisian",
  SDN: "Sudanese", PSE: "Palestinian", AFG: "Afghan",
  TZA: "Tanzanian", UGA: "Ugandan", RWA: "Rwandan", ZMB: "Zambian", ZWE: "Zimbabwean",
  SEN: "Senegalese", CMR: "Cameroonian", CIV: "Ivorian", AGO: "Angolan", MOZ: "Mozambican",
  NAM: "Namibian", SOM: "Somali", ERI: "Eritrean",
  KHM: "Cambodian", LAO: "Lao", MNG: "Mongolian", UZB: "Uzbek", TJK: "Tajik",
  KGZ: "Kyrgyz", TKM: "Turkmen", BTN: "Bhutanese", MDV: "Maldivian", BRN: "Bruneian",
  PNG: "Papua New Guinean", FJI: "Fijian",
};

export function nameToSlug(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

const byIso3 = new Map(dataset.allCountries.map((c) => [c.iso3, c]));

export interface CorridorPair { nat: string; dest: string; natSlug: string; destSlug: string }

let _pairs: CorridorPair[] | null = null;
let _useful: Set<string> | null = null;

/**
 * Curated (nationality, destination) corridors - but ONLY the ones that carry
 * genuinely differentiated content: an access grant (visa-free / VoA / eTA /
 * e-visa), freedom of movement, a VFS document checklist, OR a held-credential
 * unlock (e.g. India -> Argentina: visa required, but a valid US visa unlocks
 * entry - the page renders that whole section). Corridors that would only say
 * a generic "visa required, apply at an embassy" (no grant, no documents, no
 * unlock) are skipped so we never publish thin, near-duplicate pages.
 * Memoized so the build computes it once per worker.
 */
export function corridorPairs(): CorridorPair[] {
  if (_pairs) return _pairs;
  const out: CorridorPair[] = [];
  // Every passport (not just the curated top nationalities) gets a corridor
  // page for every destination where IT has genuine content: an access grant,
  // freedom of movement, a VFS document checklist, a credential unlock, or an
  // explicit force-include. Same thin-content bar as before - just no longer
  // capped to a curated nationality x destination grid, so "click any
  // destination card" always lands on a real per-passport page when one exists.
  // The derivation itself lives in ./corridor-dests.mjs, shared with the
  // explorer-slice build so the client "Full guide" gating can't drift.
  for (const n of dataset.allCountries) {
    const natSlug = nameToSlug(n.name);
    for (const dst of corridorDestsForNat(dataset, n.iso3)) {
      const d = byIso3.get(dst);
      if (!d) continue;
      out.push({ nat: n.iso3, dest: dst, natSlug, destSlug: nameToSlug(d.name) });
    }
  }
  _pairs = out;
  return out;
}

/**
 * The subset actually pre-rendered at build time, chosen by MEASURED search
 * demand (src/data/prerender-corridors.json, from a Search Console export).
 *
 * This used to be "top nationalities x top destinations", a curated guess.
 * Measured against real impressions, that guess pre-rendered 2,059 corridors of
 * which 92% had never received a single impression, while covering only 25.7% of
 * corridors that actually get search traffic.
 *
 * It matters because a cold corridor answers in ~0.87s versus ~0.11s cached
 * (measured in production), every deploy starts with a cold ISR cache, and
 * Googlebot throttles crawl rate on slow responses. Warming the wrong pages
 * spends crawl budget on corridors nobody searches for.
 *
 * Pre-rendering ALL of corridorPairs() is not an option: ~177 KB of output each
 * across 39,402 corridors is ~6.7 GB, which is what made deploys fail on output
 * size. Corridors outside this list are unaffected in behaviour - dynamicParams
 * is true, so they render on first visit and cache from then on.
 */
export function preWarmCorridorPairs(): CorridorPair[] {
  // UNION, not replacement. Swapping the curated grid for the measured list
  // would have cooled 1,902 corridors that are warm today - fine for cost,
  // wrong for SEO, since Googlebot crawls the whole site either way and every
  // cold page costs it another slow response. Adding is strictly better: nothing
  // regresses, and 818 corridors that actually rank stop waiting to be
  // discovered before they get fast.
  const topNat = new Set(TOP_NATIONALITIES);
  const topDest = new Set(TOP_DESTINATIONS);
  const measured = new Set(PRERENDER.corridors.map((c) => `${c.nat}|${c.dest}`));
  return corridorPairs().filter(
    (c) => (topNat.has(c.nat) && topDest.has(c.dest)) || measured.has(`${c.nat}|${c.dest}`),
  );
}

/** Fast membership check for the internal link mesh (so we never link to a pruned page). */
export function isUsefulCorridor(nat: string, dest: string): boolean {
  if (!_useful) _useful = new Set(corridorPairs().map((c) => `${c.nat}|${c.dest}`));
  return _useful.has(`${nat}|${dest}`);
}

/** Corridor pages where this country is the nationality (for the passport page's link mesh). */
export function corridorsForNationality(natIso3: string): CorridorPair[] {
  return corridorPairs().filter((c) => c.nat === natIso3);
}

/** Corridor pages where this country is the destination (for the destination page's link mesh). */
export function corridorsForDestination(destIso3: string): CorridorPair[] {
  return corridorPairs().filter((c) => c.dest === destIso3);
}
